name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Build Kernel
      shell: bash
      run: |
        if [ "$(id -u)" -eq 0 ]; then
             export SU=
         else
             export SU=sudo
         fi

        "$SU" apt-get update
        "$SU" apt-get install --no-install-recommends -y binutils git make bc bison openssl curl zip kmod cpio flex libelf-dev libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-certificates python3 xz-utils libc6-dev aria2 build-essential ccache

        ./run.sh

        mkdir build
        cp out/arch/arm64/boot/Image.gz-dtb build/
        

    - id: uploadi
      uses: actions/upload-artifact@v4
      with:
        name: kernel-built-bootimg
        path: build/*
        if-no-files-found: error
        overwrite: true
